-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.categoria_plataforma
(
    id bigint NOT NULL,
    descricao character varying(256) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.deposito
(
    id bigint NOT NULL,
    rua character varying(100) NOT NULL,
    bairro character varying(50) NOT NULL,
    cep character varying(8) NOT NULL,
    estado character varying(2) NOT NULL,
    numero integer NOT NULL,
    capacidade_total double precision NOT NULL,
    capacidade_restante double precision,
    PRIMARY KEY (id)
);

CREATE TABLE public.destinatario
(
    id bigint NOT NULL,
    nome character varying(150) NOT NULL,
    documento character varying(11) NOT NULL,
    rua character varying(100) NOT NULL,
    bairro character varying(50) NOT NULL,
    cep character varying(8) NOT NULL,
    estado character varying(2) NOT NULL,
    numero integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.funcionario
(
    id bigint NOT NULL,
    nome character varying(150) NOT NULL,
    documento character varying(11) NOT NULL,
    telefone character varying(11) NOT NULL,
    disponivel boolean NOT NULL,
    veiculo_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE public.item
(
    id bigint NOT NULL,
    descricao character varying(256) NOT NULL,
    eh_fragil boolean NOT NULL,
    volume double precision NOT NULL,
    valor_item double precision NOT NULL,
    valor_frete double precision NOT NULL,
    deposito_id bigint NOT NULL,
    servico_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.plataforma
(
    id bigint NOT NULL,
    documento character varying(14) NOT NULL,
    telefone character varying(11) NOT NULL,
    categoria_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.servico
(
    id bigint NOT NULL,
    valor_total_frete double precision NOT NULL,
    prazo_dias integer NOT NULL,
    data_limite date NOT NULL,
    data_cadastro date NOT NULL,
    data_agendada date,
    destinatario_id bigint NOT NULL,
    plataforma_id bigint NOT NULL,
    funcionario_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.veiculo
(
    id bigint NOT NULL,
    placa character varying(7) NOT NULL,
    modelo character varying(20) NOT NULL,
    cor character varying(15),
    capacidade_total double precision NOT NULL,
    capacidade_restante double precision,
    PRIMARY KEY (id)
);

ALTER TABLE public.funcionario
    ADD FOREIGN KEY (veiculo_id)
    REFERENCES public.veiculo (id)
    NOT VALID;


ALTER TABLE public.item
    ADD FOREIGN KEY (deposito_id)
    REFERENCES public.deposito (id)
    NOT VALID;


ALTER TABLE public.item
    ADD FOREIGN KEY (servico_id)
    REFERENCES public.servico (id)
    NOT VALID;


ALTER TABLE public.plataforma
    ADD FOREIGN KEY (categoria_id)
    REFERENCES public.categoria_plataforma (id)
    NOT VALID;


ALTER TABLE public.servico
    ADD FOREIGN KEY (destinatario_id)
    REFERENCES public.destinatario (id)
    NOT VALID;


ALTER TABLE public.servico
    ADD FOREIGN KEY (funcionario_id)
    REFERENCES public.funcionario (id)
    NOT VALID;


ALTER TABLE public.servico
    ADD FOREIGN KEY (plataforma_id)
    REFERENCES public.plataforma (id)
    NOT VALID;

END;